### ISSUE TITLE
compilation of command `./gradlew :library:build` fails on Mac M1

### ISSUE THREAD

**Issue by lmorek** [AVSystem/Anjay-java#1]
I have an issue while running command: `./gradlew :library:build` on Mac M1 (Monterey 12.4).
Stack trace attached 
[anjay-java.txt](https://github.com/AVSystem/Anjay-java/files/8768526/anjay-java.txt)
 
I performed `git submodule update --init --recursive` before running ./gradlew :library:build as stated in README file.

[soft_version.txt](https://github.com/AVSystem/Anjay-java/files/8768553/soft_version.txt)

**Comment by kFYatek** [comment]
Hi,

I suppose that you have Mbed TLS 3.1 installed via Homebrew.

Anjay 2.14.1 is not compatible with Mbed TLS 3.1. You can either manually upgrade the Anjay dependency to 2.15.0 (3.0 would need updating the Java integration layer, so it's not recommended for now):

```
cd native-library/deps/anjay
git checkout 2.15.0
cd ../../..
git submodule update --init --recursive
```

or alternatively, you could install Mbed TLS 2.x on your system:

```
brew install mbedtls@2
brew unlink mbedtls
brew link mbedtls@2
```

We plan on releasing an official upgrade for this integration layer shortly, which will fix this issue. Sorry for the inconvenience.

**Comment by lmorek** [comment]
Thank you for your response.
Looks like steps that you have described here works. I was able to compile and start service.

**Comment by Kushma** [comment]
Hi,
I am following the below steps in order to compile Anjay java in my Windows system.
1. git clone https://github.com/AVSystem/Anjay-java.git
2. Open Android Studio and import the project.
3. Open the terminal and run "./gradlew :library:build"
4. I am seeing the below error.
**_> Task :library:cmakeConfigure FAILED
Caching disabled for task ':library:cmakeConfigure' because:
  Caching has not been enabled for the task
Task ':library:cmakeConfigure' is not up-to-date because:
  Task has failed previously.
  CMakePlugin.task cmakeConfigure - exec: cmake -DJAVA_HOME=C:\Program Files\Java\jdk-18.0.1.1 C:\Users\KuU\Anjay-j
ava\native-library
:library:cmakeConfigure (Thread[Execution worker for ':',5,main]) completed. Took 0.04 secs.

FAILURE: Build failed with an exception.

* What went wrong:
CMakeExecutor[cmakeConfigure].
> Cannot run program "cmake" (in directory "C:\Users\KuU\Anjay-java\library\build\cmake"): CreateProcess error=2, T
he system cannot find the file specified

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings_**
-----------------------------------------------------------------------------------------------------------
Can you please help me with this issue? Also, can I get more steps so I can compile the code?
Is there a specific Java version that is needed for Anjay java to compile?
Can I compile Anjay java in Windows and Linux?
